# Generated by Django 5.1.1 on 2024-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_engagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
