# Generated by Django 5.1.1 on 2024-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_engagement", "0002_alter_message_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_id",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
