# Generated by Django 5.0.7 on 2024-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_engagement', '0003_add_message_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
