services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: essentialrecruit/judy-staging:latest
    command: daphne koda.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    container_name: chat_app

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    # image: essentialrecruit/judy-staging:latest
    command: celery -A koda worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    container_name: chat_app_celery

  redis:
    image: redis:latest
    container_name: chat_app_redis
