# Generated by Django 4.2.14 on 2024-07-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("stripe", "Stripe")], default="", max_length=10
            ),
            preserve_default=False,
        ),
    ]
