# Generated by Django 4.2.14 on 2024-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_charge_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="provider",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("stripe", "Stripe")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="provider",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("stripe", "Stripe")],
                default="stripe",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
