# Generated by Django 4.2.14 on 2024-07-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_payment_stripe_charge_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="last_payment",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="start_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("NGN", "Nigerian Naira"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="paystack_subscription_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="provider",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("stripe", "Stripe")], default="", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
