# Generated by Django 5.0.6 on 2024-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtoken',
            name='email',
            field=models.EmailField(default='resumegurupro@gmail.com', max_length=254),
        ),
    ]
