# Generated by Django 5.0.6 on 2024-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_googletoken_delete_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
