# Generated by Django 4.2.14 on 2024-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="free_usage_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="user",
            name="has_free_access",
            field=models.BooleanField(default=False),
        ),
    ]
