# Generated by Django 4.2.14 on 2024-09-04 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImprovementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OriginalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, default="General", max_length=100, null=True),
                ),
                ("file_key", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[("resume", "Resume"), ("cover_letter", "Cover Letter")],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, default="General", max_length=100, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("resume", "Resume"), ("cover_letter", "Cover Letter")],
                        max_length=20,
                    ),
                ),
                ("pdf_url", models.URLField()),
                ("docx_url", models.URLField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "job_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resume.jobdetails",
                    ),
                ),
                (
                    "original_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimized_versions",
                        to="resume.originaldocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "job_match_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interview_potential_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("ats_optimization", models.TextField()),
                ("tailoring_to_job", models.TextField(blank=True, null=True)),
                (
                    "optimized_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="resume.optimizeddocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "improvement_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_changes",
                        to="resume.improvementsummary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="improvementsummary",
            name="optimized_document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="improvement_summary",
                to="resume.optimizeddocument",
            ),
        ),
        migrations.CreateModel(
            name="DocumentCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("instruction", models.TextField()),
                ("pdf_url", models.URLField()),
                ("docx_url", models.URLField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "optimized_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customizations",
                        to="resume.optimizeddocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "customization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="resume.documentcustomization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "effectiveness_impact",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "customization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="resume.documentcustomization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="originaldocument",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="unique_user_category"
            ),
        ),
    ]
