# Generated by Django 5.0.6 on 2024-06-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField(blank=True, null=True)),
                ('general_improved_content', models.TextField(blank=True, null=True)),
                ('cover_letter_id', models.CharField(max_length=255, unique=True)),
                ('original_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('general_improved_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_id', models.CharField(max_length=255, unique=True)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('optimized_content', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField(blank=True, null=True)),
                ('general_improved_content', models.TextField(blank=True, null=True)),
                ('resume_id', models.CharField(max_length=255, unique=True)),
                ('original_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('general_improved_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoverLetterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('tone_analysis', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_matches', models.JSONField(blank=True, null=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.coverletter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('tone_analysis', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizedCoverLetterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_content', models.TextField()),
                ('optimized_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_tailored', models.BooleanField(default=False)),
                ('optimized_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.coverletteranalysis')),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.coverletter')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('tone_analysis', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_matches', models.JSONField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizedResumeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_content', models.TextField()),
                ('optimized_pdf_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_tailored', models.BooleanField(default=False)),
                ('optimized_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.jobpost')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.resumeanalysis')),
            ],
        ),
    ]
