# Generated by Django 5.0.7 on 2024-09-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizeddocument',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
