# Generated by Django 5.0.7 on 2024-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_optimizeddocument_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizeddocument',
            name='category',
        ),
        migrations.AlterField(
            model_name='originaldocument',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
