# Generated by Django 5.0.7 on 2024-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_customizationanalytics_customizationnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldocument',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
